apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian-deployment
  labels:
    app: debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debian
      #type: web
  template:
    metadata:
      labels:
        app: debian
        #type: web
    spec:
      containers:
      - name: debian
        image: tkhoa2711/debian-curl:buster-slim
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: IfNotPresent
