apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-staging-app
  namespace: argocd
spec:
  project: production
  source:
    repoURL: git@github.com:sanskar1007/argocd-assignment.git
    targetRevision: HEAD
    path: apps/overlays
  destination:
    name: gke_argo-assignment_us-central1-c_cluster-1
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true