apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.wordpress.pvc.name }}
  namespace: {{ .Values.wordpress.namespace }}
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.pvc.storage }}
