apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wordpress.service.name }}
  namespace: {{ .Values.wordpress.namespace }}
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: ClusterIP
  ports:
  {{- toYaml .Values.wordpress.service.ports | nindent 2 }}