apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-prod-app
  namespace: argocd
spec:
  project: production
  source:
    repoURL: git@github.com:sanskar1007/argocd-assignment.git
    targetRevision: HEAD
    path: apps/overlays-prod
  destination:
    name: gke_sanskar-395517_us-central1-c_gke
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true