apiVersion: batch/v1
kind: Job
metadata:
  generateName: PreSync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "https://api.flock.com/hooks/sendMessage/b53e7519-6dc4-41db-bdf6-93e60069c812"
          - "-H"
          - "Content-Type: application/json"
          - "-d"
          - '{"text": "App is about to sync"}'
      restartPolicy: Never
  backoffLimit: 2
